name: dockerhub

on:
    push:
      branches:
        - '*'
      tags:
        - '*'

jobs:
  dockerhub:
    name: push
    runs-on: ubuntu-latest
    steps:
      - name: Publish to DockerHub
        uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
        with:
            repository: vuls
            username: ohsh6o
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            tag_with_ref: true
            tag_with_sha: true

